//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
                             
namespace AssemblyCSharp
{
		public class ball
{
		private GameObject theball;
		//private int is_flying;			
		//private int length_column;
		//private int length_row;
		private int color; /*0=white 1=red 2=blue 3=green 4=yellow*/
//	public ball right;
	//public ball bottom;
		private int is_row_linked;
		private int is_column_linked;
		private int is_empty;

				public ball ()
				{
			//theball = new GameObject();
		//	is_flying = 0;
		//	length_column = 1;
			//length_row = 1;
			color = 0;
			is_row_linked=0;
			is_column_linked=0;
			is_empty = 1;
				}
		//theball
				public void settheball(GameObject o)
		{
			theball = o;
		}
		public GameObject gettheball()
		{
			return theball;
				}
		//flying
	/*public void set_flying()
	{
		is_flying=1;
	}
		public int get_flying()
		{
			return is_flying;
				}*/
		//color
		public void set_color(int i)
		{
			color=i;
		}
		public int get_color()
		{
			return color;
		}
		//row linked
		public void set_row_linked(int i)
		{
			if (i!=0)
								is_row_linked = 1;
						else
								is_row_linked = 0;
		}
		public int get_row_linked()
		{
			return is_row_linked;
		}

		//column linked
		public void set_column_linked(int i)
		{
			if (i!=0)
				is_column_linked = 1;
			else
				is_column_linked = 0;
		}
		public int get_column_linked()
		{
			return is_column_linked;
		}
	//empty
		public void set_empty(int i)
		{
			if (i!=0)
				is_empty = 1;
			else
				is_empty = 0;
		}
		public int get_empty()
		{
			return is_empty;
		}

	/*	//row length

	public int get_row()
	{
		return length_row;
		}

	public void count_row()
	{
		ball temp = this;
		while (temp.right != null)
		{
				if (temp.color==temp.right.color)
			{
				length_row++;
				temp=temp.right;
			}

		}
	}

		//column length

		public int get_column()
		{
			return length_column;
		}
		
		public void count_column()
		{
			ball temp = this;
			while (temp.bottom != null)
			{
				if (temp.color==temp.bottom.color)
				{
					length_column++;
					temp=temp.bottom;
				}
				
			}
		}*/
}
}

